=== andrew1412/website/profile/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Profile",
  "description": "Profile configuration properties",
  "type": "object",
  "properties": {
    "avatar": {
      "type": "string",
      "format": "uri",
      "pattern": "^(https)://"
    },
    "username": {
      "type": "string",
      "minLength": 1,
      "maxLength": 50
    },
    "bio": {
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "location": {
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "readme": {
      "type": "string",
      "format": "uri",
      "pattern": "^(https)://(.*)(\\.md)$"
    },
    "socialAccounts": {
      "type": "object",
      "properties": {
        "dribbble": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://dribbble.com/"
        },
        "facebook": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://steamcommunity.com/"
        },
        "github": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://anilist.co"
        },
        "instagram": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://discord.gg"
        },
        "matrix": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://simplex.chat/contact/#/"
        },
        "twitter": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://rumble.com/"
        },
        "youtube": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://youtube.com/"
        },
        "website": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://"
        },
        "mail": {
          "type": "string",
          "format": "email"
        }
      }
    },
    "banner": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "text": {
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        }
      },
      "required": ["title", "text"]
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string",
            "format": "uri",
            "pattern": "^(https)://"
          },
          "title": {
            "type": "string",
            "minLength": 1,
            "maxLength": 50
          }
        },
        "required": ["url", "title"]
      },
      "minItems": 1
    },
    "rss": {
      "type": "string",
      "format": "uri",
      "pattern": "^(https)://"
    }
  },
  "required": ["avatar", "username", "links", "bio", "socialAccounts"]
}

=== andrew1412/website/profile/profile_galeria.json
{
  "$schema": "schema.json",
  "avatar": "https://github.com/andrew1412/website/raw/main/static/logos/andrew1412.pfp.sunglasses.webp",
  "username": "Galeria",
  "links": [
    { "url": "/blog", "title": "Blog" },
    { "url": "/galeria", "title": "Galeria" },
    { "url": "https://example.com", "title": "Fotos" }
  ],
  "bio": "ðŸ“· Albums",
  "location": "Chile",
  "socialAccounts": {
    "github": "https://github.com/andrew1412",
    "youtube": "https://youtube.com/c/andrew1412",
    "twitter": "https://twitter.com/"
  },
  "banner": {
    "title": "Nuevo blog!",
    "text": "Ahora puedes entrar a mi blog y estar al dÃ­a con lo que publico."
  },
  "rss": "https://www.nasa.gov/rss/dyn/breaking_news.rss",
  "readme": "https://gist.githubusercontent.com/DomPizzie/7a5ff55ffa9081f2de27c315f5018afc/raw/d59043abbb123089ad6602aba571121b71d91d7f/README-Template.md"
}

=== andrew1412/website/profile/profile_home.json
{
  "$schema": "schema.json",
  "avatar": "https://github.com/andrew1412/website/raw/main/static/logos/pfp-1.webp",
  "username": "Andrew 1412",
  "links": [{ "url": "/blog", "title": "Blog" }],
  "bio": "üêà‚Äç‚¨õ Vtuber",
  "location": "Chile",
  "socialAccounts": {
    "github": "https://github.com/andrew1412",
    "youtube": "https://youtube.com/@andrew1412",
    "odysee": "https://odysee.com/@andrew1412"
  },
  "banner": {
    "title": "Nuevo blog!",
    "text": "Ahora puedes entrar a mi blog y estar al d√≠a con lo que publico."
  },
  "rss": "https://www.youtube.com/feeds/videos.xml?channel_id=UCZfSAkMNwkQBzzE8sm1gr9g",
  "readme": "https://raw.githubusercontent.com/andrew1412/website/main/about/sobre-mi.md"
}

=== andrew1412/website/profile/profile_500.json
{
  "$schema": "schema.json",
  "avatar": "https://github.com/andrew1412/website/raw/main/static/logos/pfp-8.webp",
  "username": "500",
  "links": [
    { "url": "https://example.com", "title": "Blog" },
    { "url": "https://example.com", "title": "Dibujos" },
    { "url": "https://example.com", "title": "Fotos" }
  ],
  "bio": "Error interno en el servidor",
  "location": "¿Como llegaste aquí?",
  "socialAccounts": {
    "github": "https://github.com/andrew1412",
    "youtube": "https://youtube.com/c/andrew1412",
    "twitter": "https://twitter.com/",
    "mail": "unserhumanomas@proton.me"
  },
  "banner": {
    "title": "Nuevo blog!",
    "text": "Ahora puedes entrar a mi blog y estar al día con lo que publico."
  },
  "rss": "https://www.nasa.gov/rss/dyn/breaking_news.rss",
  "readme": "https://gist.githubusercontent.com/DomPizzie/7a5ff55ffa9081f2de27c315f5018afc/raw/d59043abbb123089ad6602aba571121b71d91d7f/README-Template.md"
}

=== andrew1412/website/profile/profile_blog.json
{
  "$schema": "schema.json",
  "avatar": "https://github.com/andrew1412/website/raw/main/static/logos/andrew1412.pfp.glasses.webp",
  "username": "Blog",
  "links": [
    { "url": "https://example.com", "title": "Blog" },
    { "url": "https://example.com", "title": "Dibujos" },
    { "url": "https://example.com", "title": "Fotos" }
  ],
  "bio": "Posts",
  "location": "Chile",
  "socialAccounts": {
    "github": "https://github.com/andrew1412",
    "youtube": "https://youtube.com/c/andrew1412",
    "twitter": "https://twitter.com/",
    "mail": "unserhumanomas@proton.me"
  },
  "banner": {
    "title": "Nuevo blog!",
    "text": "Ahora puedes entrar a mi blog y estar al d√≠a con lo que publico."
  },
  "rss": "https://www.nasa.gov/rss/dyn/breaking_news.rss",
  "readme": "https://gist.githubusercontent.com/DomPizzie/7a5ff55ffa9081f2de27c315f5018afc/raw/d59043abbb123089ad6602aba571121b71d91d7f/README-Template.md"
}
